version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    ports:
      - 8080:8080
    links:
      - mysql
    tty:
      true
    volumes:
      - ./src/api:/go/src/api
    env_file:
      - ./docker/env

  mysql:
    container_name: mysql
    build: ./docker/mysql/
    hostname: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./docker/env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - ./docker/mysql/my.conf:/etc/mysql/my.conf
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d

